const products = [
  {
    id: 1,
    img: 'https://m.media-amazon.com/images/I/6125yAfsJKL._AC_UX575_.jpg',
    title: 'Nike Air Monarch IV',
    reviews: '4.8K',
    prevPrice: '200',
    newPrice: '150',
    brand: 'Nike',
    color: 'white',
    category: 'sneakers',
    rating: 4,
  },

  {
    id: 3,
    img: 'https://m.media-amazon.com/images/I/51+P9uAvb1L._AC_UY695_.jpg',
    title: 'Nike Waffle One Sneaker',
    reviews: '3.9K',
    prevPrice: '180',
    newPrice: '120',
    brand: 'Nike',
    color: 'green',
    category: 'sneakers',
    rating: 3.5,
  },
  {
    id: 4,
    img: 'https://m.media-amazon.com/images/I/71oEKkghg-L._AC_UX575_.jpg',
    title: 'Nike Running Shoe',
    reviews: '4.5K',
    prevPrice: '160',
    newPrice: '100',
    brand: 'Adidas',
    color: 'black',
    category: 'sneakers',
    rating: 4.2,
  },
  {
    id: 5,
    img: 'https://m.media-amazon.com/images/I/41M54ztS6IL._AC_SY625._SX._UX._SY._UY_.jpg',
    title: 'Flat Slip On Pumps',
    reviews: '3.2K',
    prevPrice: '130',
    newPrice: '80',
    brand: 'Vans',
    color: 'green',
    category: 'flats',
    rating: 3,
  },
  {
    id: 6,
    img: 'https://m.media-amazon.com/images/I/71zKuNICJAL._AC_UX625_.jpg',
    title: 'Knit Ballet Flat',
    reviews: '4.3K',
    prevPrice: '110',
    newPrice: '70',
    brand: 'Adidas',
    color: 'black',
    category: 'flats',
    rating: 4.8,
  },
  {
    id: 7,
    img: 'https://m.media-amazon.com/images/I/61V9APfz97L._AC_UY695_.jpg',
    title: 'Loafer Flats',
    reviews: '3.7K',
    prevPrice: '90',
    newPrice: '60',
    brand: 'Vans',
    color: 'white',
    category: 'flats',
    rating: 3.7,
  },
  {
    id: 8,
    img: 'https://m.media-amazon.com/images/I/71VaQ+V6XnL._AC_UY695_.jpg',
    title: 'Nike Zoom Freak',
    reviews: '4.6K',
    prevPrice: '220',
    newPrice: '170',
    brand: 'Nike',
    color: 'green',
    category: 'sneakers',
    rating: 4.9,
  },
  {
    id: 9,
    img: 'https://m.media-amazon.com/images/I/61-cBsLhJHL._AC_UY695_.jpg',
    title: "Nike Men's Sneaker",
    reviews: '4.0K',
    prevPrice: '190',
    newPrice: '140',
    brand: 'Adidas',
    color: 'blue',
    category: 'sneakers',
    rating: 4.1,
  },
  {
    id: 10,
    img: 'https://m.media-amazon.com/images/I/81xXDjojYKS._AC_UX575_.jpg',
    title: 'PUMA BLACK-OCE',
    reviews: '4.2K',
    prevPrice: '170',
    newPrice: '120',
    brand: 'Puma',
    color: 'green',
    category: 'sneakers',
    rating: 4.3,
  },
  {
    id: 11,
    img: 'https://m.media-amazon.com/images/I/71E75yRwCDL._AC_UY575_.jpg',
    title: 'Pacer Future Sneaker',
    reviews: '3.8K',
    prevPrice: '150',
    newPrice: '100',
    brand: 'Puma',
    color: 'red',
    category: 'sneakers',
    rating: 3.9,
  },
  {
    id: 12,
    img: 'https://m.media-amazon.com/images/I/71jeoX0rMBL._AC_UX575_.jpg',
    title: 'Unisex-Adult Super',
    reviews: '4.4K',
    prevPrice: '140',
    newPrice: '90',
    brand: 'Puma',
    color: 'black',
    category: 'sneakers',
    rating: 4.6,
  },
  {
    id: 13,
    img: 'https://m.media-amazon.com/images/I/61TM6Q9dvxL._AC_UX575_.jpg',
    title: 'Roma Basic Sneaker',
    reviews: '3.6K',
    prevPrice: '120',
    newPrice: '80',
    brand: 'Puma',
    color: 'white',
    category: 'sneakers',
    rating: 3.4,
  },
  {
    id: 14,
    img: 'https://m.media-amazon.com/images/I/7128-af7joL._AC_UY575_.jpg',
    title: 'Pacer Future Doubleknit',
    reviews: '4.7K',
    prevPrice: '180',
    newPrice: '130',
    brand: 'Puma',
    color: 'black',
    category: 'sneakers',
    rating: 5,
  },
  {
    id: 15,
    img: 'https://m.media-amazon.com/images/I/81xXDjojYKS._AC_UX575_.jpg',
    title: 'Fusion Evo Golf Shoe',
    reviews: '3.5K',
    prevPrice: '160',
    newPrice: '110',
    brand: 'Puma',
    color: 'green',
    category: 'sneakers',
    rating: 3.2,
  },
  {
    id: 16,
    img: 'https://m.media-amazon.com/images/I/719gdz8lsTS._AC_UX575_.jpg',
    title: 'Rainbow Chex Skate',
    reviews: '4.1K',
    prevPrice: '130',
    newPrice: '90',
    brand: 'Vans',
    color: 'white',
    category: 'flats',
    rating: 4.2,
  },
  {
    id: 17,
    img: 'https://m.media-amazon.com/images/I/71gpFHJlnoL._AC_UX575_.jpg',
    title: 'Low-Top Trainers',
    reviews: '3.9K',
    prevPrice: '100',
    newPrice: '70',
    brand: 'Vans',
    color: 'white',
    category: 'loafers',
    rating: 3.8,
  },
  {
    id: 18,
    img: 'https://m.media-amazon.com/images/I/71pf7VFs9CL._AC_UX575_.jpg',
    title: 'Vans Unisex Low-Top',
    reviews: '4.8K',
    prevPrice: '110',
    newPrice: '80',
    brand: 'Vans',
    color: 'blue',
    category: 'loafers',
    rating: 4.9,
  },
  {
    id: 19,
    img: 'https://m.media-amazon.com/images/I/61bncQ44yML._AC_UX695_.jpg',
    title: 'Chunky High Heel',
    reviews: '4.2K',
    prevPrice: '90',
    newPrice: '60',
    brand: 'Vans',
    color: 'black',
    category: 'heels',
    rating: 4.4,
  },
  {
    id: 20,
    img: 'https://m.media-amazon.com/images/I/71czu7WgGuL._AC_UY695_.jpg',
    title: 'Slip On Stiletto High Heel',
    reviews: '3.7K',
    prevPrice: '120',
    newPrice: '80',
    brand: 'Puma',
    color: 'black',
    category: 'heels',
    rating: 3.6,
  },
  {
    id: 21,
    img: 'https://m.media-amazon.com/images/I/61men05KRxL._AC_UY625_.jpg',
    title: 'DREAM PAIRS Court Shoes',
    reviews: '4.5K',
    prevPrice: '160',
    newPrice: '110',
    brand: 'Nike',
    color: 'red',
    category: 'heels',
    rating: 4.7,
  },
  {
    id: 22,
    img: 'https://m.media-amazon.com/images/I/519MRhRKGFL._AC_UX575_.jpg',
    title: 'Nike Air Vapormax Plus',
    reviews: '4.1K',
    prevPrice: '250',
    newPrice: '180',
    brand: 'Nike',
    color: 'red',
    category: 'sneakers',
    rating: 4.5,
  },
  {
    id: 23,
    img: 'https://m.media-amazon.com/images/I/51PGWTXgf-L._AC_UY625_.jpg',
    title: 'Low Mid Block Heels',
    reviews: '3.9K',
    prevPrice: '130',
    newPrice: '90',
    brand: 'Nike',
    color: 'black',
    category: 'heels',
    rating: 3.9,
  },
  {
    id: 24,
    img: 'https://m.media-amazon.com/images/I/616sA5XUKtL._AC_UY675_.jpg',
    title: 'Chunky High Heel',
    reviews: '4.3K',
    prevPrice: '100',
    newPrice: '70',
    brand: 'Adidas',
    color: 'brown',
    category: 'heels',
    rating: 4.3,
  },
  {
    id: 25,
    img: 'https://m.media-amazon.com/images/I/71h5+MbEK7L._AC_UY625_.jpg',
    title: 'Amore Fashion Stilettos',
    reviews: '3.8K',
    prevPrice: '150',
    newPrice: '100',
    brand: 'Adidas',
    color: 'white',
    category: 'heels',
    rating: 3.8,
  },
  {
    id: 27,
    img: 'https://m.media-amazon.com/images/I/71yhoZP0l6L._AC_UY695_.jpg',
    title: 'Wedding Prom Bridal',
    reviews: '3.6K',
    prevPrice: '90',
    newPrice: '60',
    brand: 'Adidas',
    color: 'black',
    category: 'heels',
    rating: 3.5,
  },
];

export default products;
